@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_000
	.align	2

wave_000:

	.hword	0x3C08, 0x0000
	.word	0x81E472C @ Mid-C pitch ~133009.79296875 Hz
	.word	0 @ Loop Start
	.word	0 @ Loop End
