@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_001
	.align	2

bank_001:

@**************** Voice 000 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_019
	.byte	255, 0, 255, 0

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_020
	.byte	255, 0, 255, 0

@**************** Voice 002 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_021
	.byte	255, 0, 255, 0

@**************** Voice 003 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+50
	.word	wave_021
	.byte	255, 0, 255, 0

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_022
	.byte	255, 0, 255, 0

@**************** Voice 005 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+50
	.word	wave_022
	.byte	255, 0, 255, 0

@**************** Voice 006 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 007 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+50
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 008 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 009 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_024
	.byte	255, 0, 255, 0

@**************** Voice 010 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_018
	.byte	255, 0, 255, 0

@**************** Voice 011 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 012 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 013 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 014 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 015 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 016 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 017 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 018 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 019 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 020 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 021 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 022 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 023 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 024 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 025 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 026 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 12, 0

@**************** Voice 027 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 028 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 029 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 030 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 031 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_025
	.byte	255, 0, 255, 0

@**************** Voice 032 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_018
	.byte	255, 0, 255, 0

@**************** Voice 033 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_026
	.byte	9, 0, 255, 0

@**************** Voice 034 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 035 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 036 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 037 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 038 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 0, 255, 0

@**************** Voice 039 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	255, 0, 255, 0

@**************** Voice 040 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 041 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_030
	.byte	255, 0, 255, 0

@**************** Voice 042 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 043 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 0, 11, 1

@**************** Voice 044 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 045 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 046 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 047 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 048 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 3, 11, 1

@**************** Voice 049 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 050 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 051 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 052 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 053 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 054 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 055 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 056 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 057 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 12, 0

@**************** Voice 058 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 059 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 060 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 061 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 062 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_018
	.byte	255, 0, 255, 0

@**************** Voice 063 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 064 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 0, 11, 1

@**************** Voice 065 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 066 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 067 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 068 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 069 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 070 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 071 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 072 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 073 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 074 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 075 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 076 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 077 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 078 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 12, 0

@**************** Voice 079 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 080 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 081 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 082 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 083 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 084 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 085 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 086 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 087 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 088 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 089 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 090 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 091 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 092 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 093 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 094 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 095 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 096 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 097 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 0, 12, 1

@**************** Voice 098 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_018
	.byte	8, 0, 255, 0

@**************** Voice 099 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 100 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 101 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 102 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 103 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0



	.end
