@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_033
	.align	2

wave_033:

	.hword	0x3C08, 0x0000
	.word	0x82069D0 @ Mid-C pitch ~133146.453125 Hz
	.word	0 @ Loop Start
	.word	0 @ Loop End
