@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_002
	.align	2

wave_002:

	.hword	0x3C00, 0x0000
	.word	0x818F374 @ Mid-C pitch ~132668.86328125 Hz
	.word	0 @ Loop Start
	.word	0 @ Loop End
