@ File generated by m4a2s Wave-Module
	.section .rodata
	.global	wave_033
	.align	2

wave_033:

	.hword	0x3C08, 0x0000
	.word	0x818E608 @ Mid-C pitch ~132665.5078125 Hz
	.word	0 @ Loop Start
	.word	0 @ Loop End
