@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	drums_000
	.align	2

drums_000:

@**************** Voice 000 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 001 ****************@

	.byte	DirectSound
	.byte	Fn5 
	.byte	0x15
	.byte	0x08
	.word	wave_000
	.byte	24, 89, 21, 8

@**************** Voice 002 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 003 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 004 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 005 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 006 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 007 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 008 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 009 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 010 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 011 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 012 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 013 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 014 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 015 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 016 ****************@

	.byte	DirectReverse
	.byte	Gn5 
	.byte	0x15
	.byte	0x08
	.word	wave_001
	.byte	40, 91, 21, 8

@**************** Voice 017 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 018 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 019 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 020 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 021 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 022 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 023 ****************@

	.byte	DirectRevFix
	.byte	Gs5 
	.byte	0x15
	.byte	0x08
	.word	wave_002
	.byte	48, 92, 21, 8

@**************** Voice 024 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 025 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 026 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 027 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 028 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 029 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 030 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 031 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 032 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 033 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 034 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 035 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 036 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 037 ****************@

	.byte	ProgNoise
	.byte	Gn4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 15, 3

@**************** Voice 038 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_003
	.byte	255, 0, 255, 204

@**************** Voice 039 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_004
	.byte	255, 0, 255, 204

@**************** Voice 040 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+50
	.word	wave_005
	.byte	255, 0, 255, 0

@**************** Voice 041 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-50
	.word	wave_006
	.byte	255, 0, 255, 0

@**************** Voice 042 ****************@

	.byte	ProgNoise
	.byte	Bn4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 11, 0

@**************** Voice 043 ****************@

	.byte	ProgNoise
	.byte	Bn4 
	.byte	0x00
	.byte	0xFF
	.word	FineNoise
	.byte	0, 1, 0, 0

@**************** Voice 044 ****************@

	.byte	ProgNoise
	.byte	Bn4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 1, 0, 0

@**************** Voice 045 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-10
	.word	wave_007
	.byte	255, 0, 255, 0

@**************** Voice 046 ****************@

	.byte	ProgNoise
	.byte	Bn4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 2, 8, 3

@**************** Voice 047 ****************@

	.byte	ProgNoise
	.byte	Gn4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	5, 5, 5, 3

@**************** Voice 048 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_008
	.byte	255, 0, 255, 0

@**************** Voice 049 ****************@

	.byte	ProgNoise
	.byte	Bn3 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 7, 0, 1

@**************** Voice 050 ****************@

	.byte	ProgNoise
	.byte	Bn3 
	.byte	0x00
	.byte	0xFF
	.word	FineNoise
	.byte	0, 7, 0, 1

@**************** Voice 051 ****************@

	.byte	ProgNoise
	.byte	Bn3 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 7, 0, 1

@**************** Voice 052 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_009
	.byte	255, 0, 255, 188

@**************** Voice 053 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_010
	.byte	255, 0, 255, 0

@**************** Voice 054 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_011
	.byte	255, 0, 255, 204

@**************** Voice 055 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_009
	.byte	128, 0, 255, 216

@**************** Voice 056 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_012
	.byte	255, 0, 255, 204

@**************** Voice 057 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-60
	.word	wave_013
	.byte	255, 0, 206, 0

@**************** Voice 058 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_014
	.byte	255, 0, 255, 0

@**************** Voice 059 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_015
	.byte	255, 0, 255, 0

@**************** Voice 060 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_016
	.byte	255, 0, 255, 204

@**************** Voice 061 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+40
	.word	wave_017
	.byte	255, 0, 255, 204

@**************** Voice 062 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-40
	.word	wave_017
	.byte	255, 0, 255, 204

@**************** Voice 063 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_018
	.byte	255, 0, 255, 204

@**************** Voice 064 ****************@

	.byte	DirectSound
	.byte	Gs2 
	.byte	0x00
	.byte	c_v-45
	.word	wave_019
	.byte	255, 0, 255, 204

@**************** Voice 065 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+10
	.word	wave_019
	.byte	255, 0, 255, 204

@**************** Voice 066 ****************@

	.byte	DirectSound
	.byte	En3 
	.byte	0x00
	.byte	c_v+45
	.word	wave_019
	.byte	255, 0, 255, 204

@**************** Voice 067 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_020
	.byte	255, 0, 255, 0

@**************** Voice 068 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_021
	.byte	255, 0, 255, 0

@**************** Voice 069 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_022
	.byte	255, 0, 255, 226

@**************** Voice 070 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 071 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_024
	.byte	255, 0, 255, 0

@**************** Voice 072 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_025
	.byte	255, 0, 255, 204

@**************** Voice 073 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_026
	.byte	255, 0, 255, 204

@**************** Voice 074 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 075 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_002
	.byte	0, 0, 13, 0

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 235, 231, 204

@**************** Voice 077 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_028
	.byte	255, 0, 255, 165

@**************** Voice 078 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 3, 6, 2

@**************** Voice 079 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 4, 6, 2

@**************** Voice 080 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 3, 6, 2

@**************** Voice 081 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 4, 6, 2

@**************** Voice 082 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 083 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	26, 0, 255, 226

@**************** Voice 084 ****************@

	.byte	AProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 13, 4

@**************** Voice 085 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 0, 15, 6

@**************** Voice 086 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 0, 15, 1

@**************** Voice 087 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 088 ****************@

	.byte	SquareWave1
	.byte	Cn3
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 089 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 6, 6, 2

@**************** Voice 090 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 7, 2

@**************** Voice 091 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 5, 7, 2

@**************** Voice 092 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 7, 2

@**************** Voice 093 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_030
	.byte	255, 0, 255, 216

@**************** Voice 094 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	255, 0, 255, 204

@**************** Voice 095 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 5, 7, 2

@**************** Voice 096 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 097 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 3, 0, 0

@**************** Voice 098 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_031
	.byte	255, 0, 255, 89

@**************** Voice 099 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 0, 255, 216

@**************** Voice 100 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 7, 4

@**************** Voice 101 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 7, 1

@**************** Voice 102 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 4

@**************** Voice 103 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 7, 1

@**************** Voice 104 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 6

@**************** Voice 105 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 6

@**************** Voice 106 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 107 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 3, 0, 0

@**************** Voice 108 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_033
	.byte	255, 0, 255, 204

@**************** Voice 109 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 2, 10, 1

@**************** Voice 110 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 111 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 0, 15, 0

@**************** Voice 112 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 0, 15, 0

@**************** Voice 113 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 114 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 0, 13, 0

@**************** Voice 115 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 0, 255, 153

@**************** Voice 116 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 4, 9, 1

@**************** Voice 117 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 7, 12, 1

@**************** Voice 118 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 119 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 120 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 0, 255, 0

@**************** Voice 121 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 9, 2

@**************** Voice 122 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 9, 2

@**************** Voice 123 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 124 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 3, 0, 0

@**************** Voice 125 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 11, 1

@**************** Voice 126 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 11, 1

@**************** Voice 127 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 0, 255, 0



	.end
