@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_000
	.align	2

bank_000:

@**************** Voice 000 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 001 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 9, 1

@**************** Voice 002 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 0, 12, 0

@**************** Voice 003 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_031
	.byte	255, 0, 255, 0

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 235, 154, 216

@**************** Voice 005 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 1, 9, 1

@**************** Voice 006 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 1, 9, 1

@**************** Voice 007 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 0, 15, 1

@**************** Voice 008 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 9, 1

@**************** Voice 009 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 010 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 4, 6, 0

@**************** Voice 011 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 4, 7, 1

@**************** Voice 012 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 4, 7, 1

@**************** Voice 013 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_034
	.byte	255, 0, 255, 0

@**************** Voice 014 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_035
	.byte	255, 242, 103, 216

@**************** Voice 015 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 226, 167, 216

@**************** Voice 016 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 6, 6, 2

@**************** Voice 017 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 6, 6, 2

@**************** Voice 018 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 15, 0

@**************** Voice 019 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 020 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 3, 6, 2

@**************** Voice 021 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_036
	.byte	255, 0, 255, 127

@**************** Voice 022 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_037
	.byte	255, 0, 255, 127

@**************** Voice 023 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 024 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 2, 10, 1

@**************** Voice 025 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 10, 1

@**************** Voice 026 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 2, 10, 1

@**************** Voice 027 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 10, 1

@**************** Voice 028 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 3, 6, 0

@**************** Voice 029 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 030 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 13, 0

@**************** Voice 031 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_038
	.byte	255, 0, 255, 127

@**************** Voice 032 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_039
	.byte	255, 165, 154, 204

@**************** Voice 033 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 2, 9, 2

@**************** Voice 034 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 4, 7, 2

@**************** Voice 035 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 2, 9, 2

@**************** Voice 036 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 4, 7, 2

@**************** Voice 037 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 038 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 3, 0, 0

@**************** Voice 039 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_040
	.byte	255, 0, 255, 165

@**************** Voice 040 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 1

@**************** Voice 041 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 1

@**************** Voice 042 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 2, 9, 3

@**************** Voice 043 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 2, 9, 3

@**************** Voice 044 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_031
	.byte	255, 0, 255, 127

@**************** Voice 045 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_040
	.byte	255, 0, 255, 216

@**************** Voice 046 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 047 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 0, 12, 1

@**************** Voice 048 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 049 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 11, 1

@**************** Voice 050 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_041
	.byte	255, 0, 255, 0

@**************** Voice 051 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 0, 255, 0

@**************** Voice 052 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 053 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 5, 7, 0

@**************** Voice 054 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 226, 206, 242

@**************** Voice 055 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 5, 10, 1

@**************** Voice 056 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty75
	.byte	0, 5, 10, 1

@**************** Voice 057 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 226, 206, 204

@**************** Voice 058 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 059 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_002
	.byte	0, 3, 6, 0

@**************** Voice 060 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 0, 255, 165

@**************** Voice 061 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	1, 0, 15, 1

@**************** Voice 062 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 0, 15, 1

@**************** Voice 063 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 064 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 0, 15, 1

@**************** Voice 065 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_003
	.byte	0, 0, 15, 3

@**************** Voice 066 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	64, 0, 255, 153

@**************** Voice 067 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 7, 2

@**************** Voice 068 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 7, 2

@**************** Voice 069 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_038
	.byte	255, 242, 154, 216

@**************** Voice 070 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	255, 0, 255, 216

@**************** Voice 071 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 5, 4, 2

@**************** Voice 072 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 5, 4, 2

@**************** Voice 073 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 4, 0, 0

@**************** Voice 074 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 2

@**************** Voice 075 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 9, 2

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_031
	.byte	255, 0, 255, 165

@**************** Voice 077 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_030
	.byte	255, 0, 255, 216

@**************** Voice 078 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 6, 4, 2

@**************** Voice 079 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 6, 4, 2

@**************** Voice 080 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 235, 154, 226

@**************** Voice 081 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_000
	.byte	0, 6, 4, 3

@**************** Voice 082 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 6, 6, 2

@**************** Voice 083 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 6, 6, 2

@**************** Voice 084 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 6, 3

@**************** Voice 085 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 5, 6, 3

@**************** Voice 086 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_032
	.byte	255, 235, 154, 165

@**************** Voice 087 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 088 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 3, 0, 0

@**************** Voice 089 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_042
	.byte	255, 0, 255, 127

@**************** Voice 090 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_043
	.byte	255, 0, 255, 127

@**************** Voice 091 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 0, 15, 1

@**************** Voice 092 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 0

@**************** Voice 093 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_029
	.byte	255, 0, 255, 127

@**************** Voice 094 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_044
	.byte	255, 0, 255, 127

@**************** Voice 095 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 096 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 3, 0, 0

@**************** Voice 097 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	1, 4, 4, 1

@**************** Voice 098 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	1, 4, 4, 1

@**************** Voice 099 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_027
	.byte	255, 235, 206, 165

@**************** Voice 100 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 3, 7, 1

@**************** Voice 101 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 3, 7, 1

@**************** Voice 102 ****************@

	.byte	DrumTable
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.word	drums_000
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 103 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 12, 0

@**************** Voice 104 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	1, 2, 10, 3

@**************** Voice 105 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	1, 2, 10, 3

@**************** Voice 106 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_045
	.byte	255, 0, 255, 216

@**************** Voice 107 ****************@

	.byte	ProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 0, 12, 4

@**************** Voice 108 ****************@

	.byte	SquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	1, 2, 10, 1

@**************** Voice 109 ****************@

	.byte	SquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	1, 2, 10, 1

@**************** Voice 110 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 2, 0, 0

@**************** Voice 111 ****************@

	.byte	ASquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty25
	.byte	0, 3, 0, 0

@**************** Voice 112 ****************@

	.byte	AProgWave
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	gbwave_001
	.byte	0, 4, 0, 0

@**************** Voice 113 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_046
	.byte	255, 0, 255, 0

@**************** Voice 114 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 0, 0

@**************** Voice 115 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 0, 0

@**************** Voice 116 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 1, 0, 0

@**************** Voice 117 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 0, 15, 0

@**************** Voice 118 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x1F
	.word	WaveDuty12
	.byte	0, 1, 0, 0

@**************** Voice 119 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_047
	.byte	255, 0, 255, 0

@**************** Voice 120 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x1F
	.word	WaveDuty12
	.byte	0, 0, 15, 0

@**************** Voice 121 ****************@

	.byte	ASquareWave2
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty12
	.byte	0, 0, 15, 0

@**************** Voice 122 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_048
	.byte	255, 0, 255, 0

@**************** Voice 123 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_049
	.byte	255, 0, 255, 0

@**************** Voice 124 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	FineNoise
	.byte	0, 2, 0, 0

@**************** Voice 125 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	RoughNoise
	.byte	0, 2, 0, 0

@**************** Voice 126 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_050
	.byte	255, 0, 255, 0

@**************** Voice 127 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_051
	.byte	255, 0, 255, 0



	.end
